### ISSUE TITLE
Need more info - what is "old package.json"?

### ISSUE THREAD

**Issue by sergeymaysak** [leCandas/M5Stamp-C3#1]
Thanks for sharing this effort!

From your description:
"Put your old "package.json" in to the extracted folder " is not really clear which one package.json do you mean? I just have in my .platformio folder a lot of packages. Attempt to try "just any" shows the following error during compile:
"Error: Could not find the package with 'platformio/tool-esptoolpy @ ~1.30200' requirements for your system 'darwin_x86_64'"

Could you please elaborate more? Thanks in advance! )

**Comment by leCandas** [comment]
Platform io already should have one try searching under:
"[USER HOME]\.platformio\packages\toolchain-riscv32-esp\package.json"

Or use mine note that its platform-dependent:
````
{
  "name": "toolchain-riscv32-esp",
  "version": "8.4.0+2021r2",
  "description": "GCC Toolchain for Espressif 32-bit RISC-V based MCUs",
  "keywords": [
    "build tools",
    "compiler",
    "assembler",
    "linker",
    "preprocessor",
    "espressif",
    "esp32",
    "esp32c3",
    "risc-v"
  ],
  "license": "GPL-2.0-or-later",
  "repository": {
    "type": "git",
    "url": "https://github.com/espressif/crosstool-NG"
  },
  "system": "windows_amd64"
}

````
