### ISSUE TITLE
Monitor does not work

### ISSUE THREAD

**Issue by VICLER** [leCandas/M5Stamp-C3#3]
Hello! Thanks for the integration of stampC3 into platformIO!

I have a stampC3 and stampC3U and flashing works perfectly with this two, but Serial Monitor does not.. Here is the output from the terminal:

--- Terminal on COM14 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
Calculated: 86b6856493d23fe741a1623c3d149a38bdf91ca0101173d85f25c3fdb6d605ee
Expected: e7bbd322b12b609ed444a0547cebdc54bbcf46aefed1e04449d9827791f3e8ab
Attempting to boot anyway...
entry 0x403ce000

at this point nothing happens.. I use the example with changing the led color by pushing the button (which works)

**Comment by nicolasdb** [comment]
hello, 
To enable Serial Monitor in platform.io you need to add these in the `.ini`

```
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1         ; this and
    -DARDUINO_USB_MODE=1                ; this to enable "USB CDC" option
```

**Comment by leCandas** [comment]
Thanks for the solution @nicolasdb
